name:                lsc
version:             0.1.3.1
github:              "foshardware/lsc"
license:             GPL-3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- aeson
- array
- arrowgant
- async
- blaze-svg
- blif
- bytestring
- cabal-file-th
- concurrent-output
- containers
- data-default
- data-default-class
- file-embed
- firrtl
- gloss
- hashable
- kan-extensions
- lef
- lens
- linear
- milp
- mmorph
- mtl
- parsec
- parsec-numbers
- SafeSemaphore
- template-haskell
- text
- time
- transformers
- vector
- vector-algorithms
- verilog


library:
  source-dirs: src

executables:
  lsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsc

tests:
  lsc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsc
    - tasty
    - tasty-hunit
    - lens
    - data-default
